### ISSUE TITLE
ESP compatibility with sodium mod (and iris mod) [Bug] 

### ISSUE THREAD

**Issue by JaxSie** [MeteorDevelopment/meteor-client#1642] opened 2021-11-03 12:08 UTC
### Describe the bug

the esp will act different, in a worst way when sodium is running. is there any way to fix it?

### Steps to reproduce

```bash
run both meteor and sodium, turn esp on (try toggle it too) and go to an animal, cow for instance. an extra "shadow" of the whole mob will be produced. doesnt really make sense but just try it.
```

### Meteor Version

0.4.6 & 0.4.5 (as far as i know) & 0.4.7 - 1326

### Minecraft Version

1.17.1 & 1.16.5 (as far as i know)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment] 2021-11-11 19:55
Related to #1259?

**Comment by JaxSie** [comment] 2021-11-12 03:07
> Related to #1259? (Like it's a similar issue)

yes i believe its the same issue

**Comment by RedCarlos26** [comment] 2021-11-23 19:41
Try using the latest sodium version and the latest meteor dev build and see if it's still happening @JaxSie

**Comment by JaxSie** [comment] 2021-11-24 09:23
> Try using the latest sodium version and the latest meteor dev build and see if it's still happening @JaxSie

yes its basically fix, the extra shadowing is gone. just that it wont show/highlight mobs underground. not much of a big deal but is good to see it happen. thx for the fix :D

**Comment by RedCarlos26** [comment] 2021-11-24 14:52
Perfect!

**Comment by MineGame159** [comment] 2022-01-02 13:19
Duplicate of #1259.

**Closed by MineGame159** 2022-01-02 13:19 UTC
Labels: bug
