### ISSUE TITLE
[Bug] Proxy doesn't work

### ISSUE THREAD

**Issue by ervz1** [MeteorDevelopment/meteor-client#2454] opened 2022-06-26 11:28 UTC
### Describe the bug

None of the proxies are working. Minecraft can't load motds and can't connect to the servers. There are no crashes or errors, just no connection.

### Steps to reproduce

```bash
Setting any working proxy client won't connect to it.
```

### Meteor Version

0.5.0 dev

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment] 2022-06-27 00:26
This is most likely caused by your location, try finding a proxy server closer to your location.

**Comment by yeeterlol** [comment] 2022-06-28 20:12
Same issue that happended to me!

**Comment by AlexNomadrg** [comment] 2022-06-29 18:13
I have similar issue, though i get error in console. I created isue on github two weeks ago https://github.com/MeteorDevelopment/meteor-client/issues/2415.

**Comment by BitorBit1** [comment] 2022-07-02 19:13
i have same problem

**Comment by MineGame159** [comment] 2022-07-03 13:10
Fixed in 401f6deeb9bbdfa411d7b0533564d327d2e55417.

**Closed by MineGame159** 2022-07-03 13:10 UTC
Labels: bug
