### ISSUE TITLE
[Suggestion] Make a module just like Stash Finder, but for all blocks.

### ISSUE THREAD

**Issue by DomiPieKoli** [MeteorDevelopment/meteor-client#3714] opened 2023-06-10 15:46 UTC
### Describe the feature

This will help bypass many anti-cheat plugins

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Pxddyk45** [comment] 2023-06-10 15:46
Meteor won't add bypasses for AntiCheat, so no.

**Comment by Big-Iron-Cheems** [comment] 2023-06-10 15:50
1. We don't do bypassess.
2. You can already locate blocks, I don't really see the point of also logging them to a file.

Also quite sure this is a duplicate of a previously closed issue.

**Closed by Big-Iron-Cheems** 2023-06-10 15:50 UTC
Labels: enhancement
