### ISSUE TITLE
seed ore finder 

### ISSUE THREAD

**Issue by nogamertag1011** [MeteorDevelopment/meteor-client#2630] opened 2022-08-07 09:59 UTC
### Describe the feature

its where you enter the world seed into the bar and then it will show you where ore are naturally spawned.{u may or may not have this future} 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by C10udburst** [comment] 2022-08-07 10:01
duplicate of #1890, duplicate of #1903, duplicate of #1665, duplicate of #1549, duplicate of #1405, duplicate of #537, duplicate of #1102

**Comment by I-Got-You-Dead** [comment] 2022-08-07 21:35
> duplicate of #1890, duplicate of #1903, duplicate of #1665, duplicate of #1549, duplicate of #1405, duplicate of #537, duplicate of #1102

And is in rejects

**Closed** 2022-08-09 14:56 UTC
Labels: enhancement

**Comment by PlatoStuff** [comment] 2026-04-16 18:23
> duplicate of [#1890](https://github.com/MeteorDevelopment/meteor-client/issues/1890), duplicate of [#1903](https://github.com/MeteorDevelopment/meteor-client/issues/1903), duplicate of [#1665](https://github.com/MeteorDevelopment/meteor-client/issues/1665), duplicate of [#1549](https://github.com/MeteorDevelopment/meteor-client/issues/1549), duplicate of [#1405](https://github.com/MeteorDevelopment/meteor-client/issues/1405), duplicate of [#537](https://github.com/MeteorDevelopment/meteor-client/issues/537), duplicate of [#1102](https://github.com/MeteorDevelopment/meteor-client/issues/1102)

well its not a feature is it? so we have to keep saying it
