### ISSUE TITLE
[Suggestion] Autowither

### ISSUE THREAD

**Issue by RiftyM8** [MeteorDevelopment/meteor-client#915] opened 2021-06-03 04:21 UTC
**Describe the feature**
Autowither auto places withers fast, while naming them.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by StormyBytes** [comment] 2021-06-03 04:24
Autowither:
- Duplicate of #516 
- resolved by #908 

autonametag, already exists

**Closed** 2021-06-04 23:38 UTC
Labels: enhancement
