### ISSUE TITLE
[Bug] Search rendering outside of your render distance

### ISSUE THREAD

**Issue by 453452hw** [MeteorDevelopment/meteor-client#795] opened 2021-05-20 13:53 UTC
**Describe the bug**
search config not affect blocks outside of render distance

**Screenshots**
![image](https://user-images.githubusercontent.com/59623580/118990833-851c2280-b983-11eb-8b31-5731c95289bf.png)

**Comment by RedCarlos26** [comment] 2021-11-10 21:04
Can confirm on latest version

**Comment by RedCarlos26** [comment] 2021-11-10 21:05
Duplicate of #699 @arlomcwalter

**Comment by 453452hw** [comment] 2021-11-10 21:06
damn this still aint fixed. this was fucking may

**Comment by RedCarlos26** [comment] 2021-11-10 21:33
Yea pls close since it's a duplicate

**Closed** 2021-11-10 21:39 UTC
Labels: bug
