### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 2MinuteNoodled** [MeteorDevelopment/meteor-client#387] opened 2021-03-31 21:33 UTC
Crystal aura on multi targeting mak ed you spam click an invisible entity you can see if particles are turned on and your in a pvp zone

**Comment by RedCarlos26** [comment] 2021-04-01 23:37
I cannot reproduce

**Comment by RedCarlos26** [comment] 2021-04-05 04:10
This is probably a config issue. This can be closed in my opinion because it is not relevant.

**Comment by Declipsonator** [comment] 2021-04-24 17:43
> This is probably a config issue. This can be closed in my opinion because it is not relevant.

Just because it doesn't happen to you doesn't mean it won't happen to someone else

**Comment by Declipsonator** [comment] 2021-04-24 17:43
multi targeting has been bugged before

**Comment by RedCarlos26** [comment] 2021-04-25 22:07
Hmm

**Closed** 2021-04-26 20:53 UTC
Labels: bug
