### ISSUE TITLE
[Bug] Can't add or switch Microsoft accounts.

### ISSUE THREAD

**Issue by catches** [MeteorDevelopment/meteor-client#3001] opened 2022-11-28 15:16 UTC
### Describe the bug

When joining 1.19.2 servers, I always get this:
![image](https://user-images.githubusercontent.com/105005455/204311953-e804b1eb-2ef7-47bf-b646-1bb96a5d7d31.png)

### Steps to reproduce

```bash
Switch or add Microsoft accounts, join a 1.19.2 server.
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by wmantly** [comment] 2022-12-23 20:43
This is a duplicate of #2598

**Closed** 2023-03-11 00:00 UTC
Labels: bug
