### ISSUE TITLE
Cyrillic characters [Bug] 

### ISSUE THREAD

**Issue by Nekiplay** [MeteorDevelopment/meteor-client#2279] opened 2022-05-10 16:36 UTC
### Describe the bug

Cyrillic characters don't work in text fields

### Steps to reproduce

```bash
Meteor UI
```

### Meteor Version

0.4.9-1473

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Sersoid** [comment] 2022-05-10 19:59
Duplicate of #333

**Closed** 2022-05-11 14:56 UTC
Labels: bug
