### ISSUE TITLE
Suggestion Piston Aura

### ISSUE THREAD

**Issue by Roxy333** [MeteorDevelopment/meteor-client#501] opened 2021-04-14 16:42 UTC
**Describe the feature**
Piston Aura helps with killing people with end crystals it will automatically place pistons and redstone blocks against end crystals to kill players in anti-crystal holes faster instead of having to mine the obsidian

**Screenshots**
-

**Additional info**
-

**Comment by Roxy333** [comment] 2021-04-14 16:46
just found comment 415 and 499 nice

**Comment by RedCarlos26** [comment] 2021-04-14 19:42
Duplicate of #415

**Closed** 2021-04-15 02:50 UTC
Labels: enhancement
