### ISSUE TITLE
[Suggestion] Baritone API support

### ISSUE THREAD

**Issue by LordVertice** [MeteorDevelopment/meteor-client#2732] opened 2022-09-07 16:37 UTC
### Describe the feature

Allow for users to install their own (updated or modified) version of baritone, such as development releases and experimental bugfixes. Meteor should check if baritone is installed and only load its own version if that is not the case.

Optionally, allow users to manually disable baritone (as a module or text-only config option) in case the selection doesn't work.

This feature would allow us to use important bugfixes that are yet to be fully released, such as cabaletta/baritone#3592, and it shouldn't come with any drawbacks.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment] 2022-09-07 16:47
As good as that sounds I am not aware of a way to do this apart from having 2 downloads (one with Baritone and one without). If someone has some ideas or solutions I will gladly listen.

**Comment by LordVertice** [comment] 2022-09-07 17:20
> I am not aware of a way to do this

Do you mean detecting if Baritone is installed separately, or disabling the built-in one?

The latter depends on how you implemented baritone into meteor, I can't really help you with that. The former doesn't seem too difficult, maybe the post below might help? I'm not a fabric dev myself, but it seems to make sense.

https://forums.minecraftforge.net/topic/89396-115-check-if-mod-is-loaded-solved/

**Comment by MineGame159** [comment] 2022-09-07 17:25
The problem is disabling it, we include Baritone just as a jar inside the Meteor jar and Fabric Loader handles the loading of it.

**Comment by LordVertice** [comment] 2022-09-07 18:29
Well that's beyond what I can personally help you with. I think we should keep this suggestion open until someone with the right knowledge comes along.

**Comment by StormyBytes** [comment] 2022-10-21 08:23
The PR was merged

**Closed by StormyBytes** 2022-10-21 08:23 UTC
Labels: enhancement
