### ISSUE TITLE
[Suggestion] Warn players of spectators

### ISSUE THREAD

**Issue by tomasventura13** [MeteorDevelopment/meteor-client#1298] opened 2021-07-26 20:14 UTC
The client is amazing but I have been thinking of a new functionality that warns the player when someone enters spectator mode, the client could notice that based of the tab, (when the username turns into italic), so if there is someone using spectator mode, maybe watching you, you would know it.
It could warn the player by using the chat
It's that simple

(Tho I don't know if it would work with a server with a different tab, or a plugin that doesn't let you see it)
But it should work at least in vanilla

**Comment by RedCarlos26** [comment] 2021-07-27 04:25
Duplicate of #1294

**Closed** 2021-07-27 22:12 UTC
Labels: enhancement
