### ISSUE TITLE
[Bug] No Fall not working with Flight

### ISSUE THREAD

**Issue by ollyw123** [MeteorDevelopment/meteor-client#1097] opened 2021-06-21 18:12 UTC
**Describe the bug**
when flying and pressing shift with no fall enabled you can still take fall damage

**To Reproduce**
Steps to reproduce the behaviour:
1. turn no fall and flight on
2. press and hold shift
3. take damage

**Expected behaviour**
takes no fall damage

**Additional context**
i am on the most recent dev build

**Comment by seasnail8169** [comment] 2021-06-21 18:21
This always happened right?

**Comment by ollyw123** [comment] 2021-06-21 18:27
everytime i tried it

**Comment by ollyw123** [comment] 2021-06-21 20:06
Yes everytime i tried it same outcome

**Comment by seasnail8169** [comment] 2021-06-22 07:18
i meant with older versions

**Comment by ollyw123** [comment] 2021-06-22 07:34
This happened on ver 1101

**Comment by MathiasDevelopes** [comment] 2021-07-25 12:19
Me & my friend are also getting the same outcome, and it's very annoying.

**Comment by PollastreGH** [comment] 2021-08-06 22:41
Same, would like to note that if you toggle off fly, nofall acts as intended. But if you go down with shift while fly is still turned on, you take fall damage

**Comment by zearp** [comment] 2021-08-12 20:51
Holding shift is compounding fall damage, it also happens with mobs dangling from a lead. Once you cut the lead all the damage collected will be inflicted at once.

This also happens here. Fly up and then go down with shift, the longer you shift down the more damage you take once you hit the ground or even mid air if you disable flight.

Not sure if this always has been the case, I just got into clients and anarchy servers.

**Comment by zearp** [comment] 2021-08-12 20:57
Holding shift is compounding fall damage, it also happens with mobs dangling from a lead. Once you cut the lead all the damage collected will be inflicted at once.

This also happens here. Fly up and then go down with shift, the longer you shift down the more damage you take once you hit the ground or even mid air if you disable flight.

With no fall disabled this doesn't happen.

**Comment by MathiasDevelopes** [comment] 2021-08-14 12:24
> 
> 
> Same, would like to note that if you toggle off fly, nofall acts as intended. But if you go down with shift while fly is still turned on, you take fall damage

I am also experiencing when i have flight and nofall enabled, and I disable flight, it will push me towards the ground really fast and I will take damage, even in the water.

**Comment by soshimee** [comment] 2022-02-08 07:16
for me it only sometimes happens, but when it happens I die, so it's crucial

**Comment by Bluscream** [comment] 2022-02-08 08:32
it happens when you hold shift to descent until you hit the ground

**Closed** 2022-08-22 13:04 UTC
Labels: bug

**Comment by Bluscream** [comment] 2022-08-23 13:42
Good that this was fixed
