### ISSUE TITLE
[Bug] OpenGL Error 1282 when using Meteor

### ISSUE THREAD

**Issue by ItsNiceCraft** [MeteorDevelopment/meteor-client#2217] opened 2022-04-09 16:45 UTC
### Describe the bug

While ingame using the meteor client, it spams my logs with the following:

`OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'`

This only happens while playing meteor client (latest) on 1.18.2 and 1.18.1. I know this error is generic and there's nothing much you can do with it but I don't want to play with a client that spams my logs really bad.

### Steps to reproduce

```bash
Play with Meteor on the latest version
```

### Meteor Version

Release 0.4.8

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment] 2022-04-09 16:46
Duplicate of #1175.

**Closed by MineGame159** 2022-04-09 16:46 UTC
Labels: bug
