### ISSUE TITLE
[SUGGESTION]  long jump

### ISSUE THREAD

**Issue by coolsvestka** [MeteorDevelopment/meteor-client#487] opened 2021-04-12 18:00 UTC
**Describe the feature**
long jump would be usefull

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by seasnail8169** [comment] 2021-04-12 18:40
Duplicate of #440

**Closed** 2021-04-12 18:41 UTC
Labels: enhancement
