### ISSUE TITLE
Add potion effects to nametags

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#1250] opened 2021-07-17 17:55 UTC
Meteor nametags should also display potion effects, along with the amount of time remaining.

**Comment by LDoom** [comment] 2021-07-18 00:14
target hub add this, no nametag

**Comment by BowenGIT** [comment] 2021-07-18 03:43
@LDoom can you please clarify?

**Comment by LDoom** [comment] 2021-07-18 04:35
> @LDoom can you please clarify?

Add effects here 
![image](https://user-images.githubusercontent.com/73355762/126055836-88826f50-fada-486c-a5bf-57ce7f1623c9.png)

@MineGame159

**Comment by StormyBytes** [comment] 2021-07-18 12:42
Duplicate of #797

**Comment by StormyBytes** [comment] 2022-10-08 12:34
closed because duplicate

**Closed by StormyBytes** 2022-10-08 12:34 UTC
Labels: enhancement
