### ISSUE TITLE
[Suggestion] Autocrafting

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1211] opened 2021-07-12 00:31 UTC
Module that would automatically craft one or many configured blocks with a specified amount when entering a crafting table
Would be useful for crafting shulkerboxes of crystals or gold blocks from nuggets for example

**Comment by dadudeme** [comment] 2021-07-12 14:10
Itemscroller masa

**Comment by TyraVex** [comment] 2021-07-12 17:09
> Itemscroller masa

Thanks, this makes the crafting easier
However, I am looking for a fully afkable way to craft gold blocks from my gold farm, which produces around 1 million nuggets per day. Even with this https://www.curseforge.com/minecraft/mc-mods/easiercrafting it's really painful.
I could break the chests and craft them all, but directly storing gold blocks instead of nuggets takes so much less storage, and it is way easier
Same story for crystals mass crafting

**Comment by D3V1LC0D3R** [comment] 2021-07-17 15:44
dupe of #1091 ?

**Comment by TyraVex** [comment] 2021-07-19 20:07
> dupe of #1091 ?

I think yeah
It's more than autocrafting though
Im suggesting something afkable here

**Comment by dadudeme** [comment] 2021-07-21 21:59
> fully afkable

use a autoclicker with the craft and throw of itemscroller. Try tweakeroo's. this should work though will definetly be buggy on paper.

**Comment by TyraVex** [comment] 2021-07-23 02:03
> > fully afkable
> 
> use a autoclicker with the craft and throw of itemscroller. Try tweakeroo's. this should work though will definetly be buggy on paper.

I'll try it out thanks
But it would be way simpler if it becomes a feature ngl xD

**Comment by RedCarlos26** [comment] 2021-09-01 13:36
Duplicate of #1038

**Closed** 2021-11-04 12:38 UTC
Labels: enhancement
