### ISSUE TITLE
Cyrillic characters are not visible when using the custom font

### ISSUE THREAD

**Issue by imadraude** [MeteorDevelopment/meteor-client#2898] opened 2022-10-22 21:11 UTC
### Describe the bug

just a blank space is displayed instead of Cyrillic characters
![2022-10-23_00 10 42](https://user-images.githubusercontent.com/59265133/197362588-06ae7991-5242-4c42-8859-424c5a6a4208.png)
![2022-10-23_00 10 19](https://user-images.githubusercontent.com/59265133/197362589-0faa212c-cc1d-477d-971b-65d03d1ed23f.png)

### Steps to reproduce

```bash
type any Cyrillic text in any Meteor Client's text field
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment] 2022-10-23 00:57
see #333

**Comment by StormyBytes** [comment] 2022-10-23 15:10
Duplicate of #333

**Closed by StormyBytes** 2022-10-23 15:10 UTC
Labels: bug
