### ISSUE TITLE
Make Jesus work with anticheats

### ISSUE THREAD

**Issue by PilaCiu** [MeteorDevelopment/meteor-client#1234] opened 2021-07-14 16:54 UTC
Meteor client is the only utility mod without functional Jesus on NCP/AAC, can you fix this?

**Comment by RickyTheRacc** [comment] 2021-07-14 18:07
Also ncp scaffold 🙏

**Comment by mmvanheusden** [comment] 2021-07-15 11:27
Yes this would be very useful

**Comment by D3V1LC0D3R** [comment] 2021-07-17 15:18
@RickyTheRacc try using the rotate option or try walking in different angles

**Comment by D3V1LC0D3R** [comment] 2021-07-17 15:20
an option maybe to make the water solid after 1/2 block or even 1/16 that might work. another option may be to spam the swim/space key

**Comment by D3V1LC0D3R** [comment] 2021-07-17 15:35
duplicate of #556

**Comment by RedCarlos26** [comment] 2021-09-01 13:29
These duplicates I swear 😅

**Comment by RedCarlos26** [comment] 2021-09-14 01:00
@seasnail8169 this is a duplicate

**Closed** 2021-09-14 07:18 UTC
Labels: enhancement
