### ISSUE TITLE
[BUG] Taking dmg during flight (even with NOFALL)

### ISSUE THREAD

**Issue by DEIM05** [MeteorDevelopment/meteor-client#1247] opened 2021-07-17 04:56 UTC
**Describe the bug**
Still take damage using Flight even with no fall after hitting the ground or even while midair(multiplayer server)

**To Reproduce**
1. Go to/click on "flight" hack, use these settings (it may be the same on other settings i have not tested)
<img width="864" alt="Screen Shot 2021-07-17 at 2 40 32 pm" src="https://user-images.githubusercontent.com/87557927/126025923-60d1400f-0126-4e83-a831-96224898f315.png">
2. turn on nofall: packet 
4. Fly around and see damage from hitting a block, landing on a block or just movement in general 

**Expected behavior**
I expect to be able to fly without taking damage from hitting the ground or walls

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc

other mods, nothing that would be obviously conflicting
<img width="610" alt="Screen Shot 2021-07-17 at 2 50 24 pm" src="https://user-images.githubusercontent.com/87557927/126025962-3f957792-d6c9-4f08-b6e5-929d99b5497d.png">
).

**Comment by D3V1LC0D3R** [comment] 2021-07-17 15:16
the normal bypass mode has the same problem (though i think this is only on 1.17 but im not sure)

**Comment by D3V1LC0D3R** [comment] 2021-07-17 15:34
this is a duplicate of #1097

**Closed** 2021-07-27 14:08 UTC
Labels: bug
