### ISSUE TITLE
[Suggestion] SeedRay

### ISSUE THREAD

**Issue by Z3r0ut** [MeteorDevelopment/meteor-client#1102] opened 2021-06-23 01:36 UTC
**Describe the feature**
I have found a client "Aristois" that has a feature in its donor version named "SeedRay"
SeedRay is a module that bypasses Anti-xray with the seed of the map.

**Comment by C10udburst** [comment] 2021-06-23 09:59
Duplicate of #537

**Closed** 2021-06-24 12:32 UTC
Labels: enhancement
