### ISSUE TITLE
Add cev breaker

### ISSUE THREAD

**Issue by jewish5959** [MeteorDevelopment/meteor-client#1764] opened 2021-12-06 12:12 UTC
### Describe the feature

cev breaker uwu

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by StormyBytes** [comment] 2021-12-06 12:17
Correction,
- [ ] This wasn't already suggested
(I have not checked every suggestion on github)

Cev breaker was already suggested.
Duplicate of #990

**Comment by jewish5959** [comment] 2021-12-06 12:27
troll ok

**Comment by RedCarlos26** [comment] 2021-12-23 07:15
@arlomcwalter close please

**Closed** 2021-12-23 14:51 UTC
Labels: enhancement
