### ISSUE TITLE
Chinese font rendering problem

### ISSUE THREAD

**Issue by K1jinSeija** [MeteorDevelopment/meteor-client#3973] opened 2023-08-20 14:06 UTC
### Describe the bug

This mod text renderer cannot render Chinese properly

### Steps to reproduce

```bash
The Chinese characters entered in the mod text input field appear blank
```

### Meteor Version

Dev Build 0.5.4

### Minecraft Version

1.20

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Fiz-Victor** [comment] 2023-08-20 18:53
Duplicate of #333

**Closed** 2023-08-20 18:56 UTC
Labels: bug
