### ISSUE TITLE
[Suggestion] Phase Module

### ISSUE THREAD

**Issue by xzkael18** [MeteorDevelopment/meteor-client#1681] opened 2021-11-15 09:27 UTC
### Describe the feature

Let's you go through any blocks using packet fly. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by StormyBytes** [comment] 2021-11-15 09:44
*sigh*
duplicate of #475, #518, #546, #615, #747, #919, #1035

**Closed** 2021-11-15 20:52 UTC
Labels: enhancement
