### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by FJDSAIFASDFOJSA** [MeteorDevelopment/meteor-client#1077] opened 2021-06-18 15:47 UTC
**Describe the feature**
Hello dear developers! You can please add the Potion function to the NameTags section. This function makes it possible to see what kind of potions the enemy is under. This function is in the Inertia mod, but I really want this function in the Meteor client.

**Screenshots**
https://ibb.co/PZ7HpKq

**Additional info**
Best regards, James.

**Comment by StormyBytes** [comment] 2021-06-18 16:01
Duplicate of #797

**Comment by FJDSAIFASDFOJSA** [comment] 2021-06-18 16:06
I beg your pardon, I did not know about this.

**Closed** 2021-06-20 00:37 UTC
Labels: enhancement
