### ISSUE TITLE
dying in mid air

### ISSUE THREAD

**Issue by ollyw123** [MeteorDevelopment/meteor-client#1098] opened 2021-06-22 07:49 UTC
**Describe the bug**
when you have air place no fall and packet fly on you can die in mid-air

**To Reproduce**
1. fly up using packet fly and no fall
2. turn airplace on
3. then hold shift and turn packet fly off
4. die in the sky instantly

**Expected behavior**
fall without taking damage

**Screenshots**

![image](https://user-images.githubusercontent.com/86174124/122885029-9a93bc00-d336-11eb-87f2-982b23afc856.png)

**Additional context**
this happend on ver 1102 of meteor

**Comment by ollyw123** [comment] 2021-06-22 07:51
![image](https://user-images.githubusercontent.com/86174124/122885485-0aa24200-d337-11eb-98c9-dc8c4dd3f54b.png)
this is a better image

**Comment by MineGame159** [comment] 2021-06-22 12:27
Duplicate of #1097

**Closed by MineGame159** 2021-06-22 12:27 UTC
Labels: bug

**Comment by ollyw123** [comment] 2021-06-23 17:51
have you made any progress on this bug
