### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LemonNotLime** [MeteorDevelopment/meteor-client#2046] opened 2022-02-11 18:55 UTC
### Describe the bug

Game crashes randomly when launching and you have to restart the launcher to get it working again
[crash-2022-02-11_20.48.44-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8050957/crash-2022-02-11_20.48.44-client.txt)

### Steps to reproduce

```bash
Just sometimes randomly when launching the game
```

### Meteor Version

0.4.7 dev build 1405 but ive had this issue on every 0.4.7+ build

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by C10udburst** [comment] 2022-02-11 19:06
`meteor-crash-addon` is not compatible with 1.18.1

**Comment by LemonNotLime** [comment] 2022-02-11 19:07
hmm i see, ty

**Comment by Justgamer101** [comment] 2022-02-11 20:59
> hmm i see, ty

if the issue is resolved, close it

never should've been opened in the first place since it has nothing to do with meteor client crashing, but an addon

**Comment by LemonNotLime** [comment] 2022-02-12 12:02
nvm, still happens with out them

**Comment by Justgamer101** [comment] 2022-02-14 21:34
remove all addons, launch with only meteor and the fabric api installed

**Closed** 2022-03-03 16:59 UTC
Labels: bug
