### ISSUE TITLE
[Bug] offhand and replenish in 1.17+ meteor

### ISSUE THREAD

**Issue by Kiriyaga05** [MeteorDevelopment/meteor-client#1352] opened 2021-08-08 10:28 UTC
Only with 1.17+ meteor, 1.16 is ok
https://youtu.be/YyiAP8SMvs8

Also replenish buggy like offhand

**Comment by GoldenAureuz** [comment] 2021-08-10 00:37
^^^^^^^

**Comment by RedCarlos26** [comment] 2021-08-11 22:12
Yes pls fix

**Comment by LDoom** [comment] 2021-08-12 00:50
This happens to me when I have Inventory tweaks activated

> Only with 1.17+ meteor, 1.16 is ok
> https://youtu.be/YyiAP8SMvs8
> 
> Also replenish buggy like offhand

It happens to me when I have the inventory tweaks activated

**Comment by GoldenAureuz** [comment] 2021-08-31 20:03
I hate this bug so damn much

**Comment by RedCarlos26** [comment] 2021-09-01 13:24
Duplicate of #1840

**Comment by GoldenAureuz** [comment] 2021-09-02 20:34
> 
> 
> Duplicate of #1340

Yeah, it should also be noted that this bug persists even without autoreplenish.

**Comment by RedCarlos26** [comment] 2021-09-08 22:14
@seasnail8169 ^^

**Comment by seasnail8169** [comment] 2021-09-13 14:16
cry more

**Closed** 2021-09-13 18:49 UTC
Labels: bug
