### ISSUE TITLE
killaura works extremely bad on test.2b2t.org

### ISSUE THREAD

**Issue by UnknownAstronaut** [MeteorDevelopment/meteor-client#369] opened 2021-03-29 14:37 UTC
**Describe the bug**
Hill aura hits air and can't damage the player

**Expected behavior**
Make it hit players,

**Comment by RedCarlos26** [comment] 2021-03-29 21:13
It is a config or anti-cheat issue. Meteor kill aura works fine.

**Comment by AstroOrbis** [comment] 2021-03-29 22:22
Can confirm, it works perfectly on all the servers I've tested it on. Please close if you have no further comment.

**Comment by seasnail8169** [comment] 2021-03-29 23:09
Mr Issue Manager above

**Comment by RedCarlos26** [comment] 2021-03-30 02:51
> Mr Issue Manager above

Huh?

**Comment by AstroOrbis** [comment] 2021-03-30 03:23
> Mr Issue Manager above

Tryna get everything sorted lmao... the KA on the client is actually probably one of the best I've seen so...

**Comment by RedCarlos26** [comment] 2021-03-30 03:45
Yes meteor la is really good

**Comment by RedCarlos26** [comment] 2021-04-03 02:52
This is not a bug, it is a anti-cheat related issue (or config issue). @seasnail8169

**Comment by RedCarlos26** [comment] 2021-04-05 04:23
I would say this is a wont fix. We can close it @UnknownAstronaut

**Comment by supakeks** [comment] 2021-04-06 01:45
> **Describe the bug**
> Hill aura hits air and can't damage the player
> 
> **Expected behavior**
> Make it hit players,

? It hits players, it's just that 2b has an anticheat.

If you have criticals on, turn it off, current Meteor crits don't work on 2b/updated ncp
Also, get the latest dev build in the discord server's dev-builds channel and in kill aura make the rotation mode "Always"

**Comment by RedCarlos26** [comment] 2021-04-15 03:36
2b test server is not even online anymore.

**Comment by RedCarlos26** [comment] 2021-04-17 06:02
I guess this can probably be closed

**Closed** 2021-04-19 13:55 UTC
Labels: bug
