### ISSUE TITLE
.give command

### ISSUE THREAD

**Issue by xMixerek** [MeteorDevelopment/meteor-client#3385] opened 2023-02-28 16:27 UTC
### Describe the bug

So basically `.give` command have a limit of 255 characters.
Please bring back a old unlimited characters.

### Steps to reproduce

```bash
Write anything that has more than 255 charcters.
You will notice that in chat box everything will look good, but after you "send" a command you will get an error.
```

### Meteor Version

0.5.2-1781

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DesiCow** [comment] 2023-02-28 16:53
Duplicate of #3339, #3346

**Closed** 2023-03-11 17:16 UTC
Labels: bug
