### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by MassivebutterpapperCodes** [MeteorDevelopment/meteor-client#3863] opened 2023-07-21 17:39 UTC
### Describe the bug

I went to download meteor, until it said it was down

### Steps to reproduce

```bash
I did'nt do it
```

### Link to crash report/log if applicable (https://mclo.gs)

Congratulations! You've successfully started the Nginx Proxy Manager.  If you're seeing this site then you're trying to access a host that isn't set up yet.  Log in to the Admin panel to get started.

### Meteor Version

i cant see it

### Minecraft Version

i cant see it

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Paddyk45** [comment] 2023-07-21 17:40
Liar, you did it

**Comment by MassivebutterpapperCodes** [comment] 2023-07-21 17:41
do what

**Comment by MassivebutterpapperCodes** [comment] 2023-07-21 17:42
?

**Comment by MassivebutterpapperCodes** [comment] 2023-07-21 17:46
![proof](https://github.com/MeteorDevelopment/meteor-client/assets/134733276/17e6f6b9-2b2e-483d-8b5a-6dcd7099d370)

**Comment by Wide-Cat** [comment] 2023-07-21 17:46
https://nightly.link/MeteorDevelopment/meteor-client/suites/14369173626/artifacts/809475905

**Comment by Big-Iron-Cheems** [comment] 2023-07-21 17:46
>  This bug wasn't already reported (I have searched bug reports on GitHub).

Duplicate of #3862

**Comment by MassivebutterpapperCodes** [comment] 2023-07-21 17:47
oh i didnt see that post

**Comment by MassivebutterpapperCodes** [comment] 2023-07-21 17:47
ok ill delete it

**Closed by Wide-Cat** 2023-07-21 17:46 UTC
Labels: bug

**Comment by MassivebutterpapperCodes** [comment] 2023-07-21 17:47
wait i cant

**Comment by MassivebutterpapperCodes** [comment] 2023-07-21 17:48
k
