### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by CashierNub** [MeteorDevelopment/meteor-client#2225] opened 2022-04-17 20:17 UTC
### Describe the feature

can you make a mod list of all the versions of meteor?, multiconnect doesnt support 1.18.2 and i wanna troll my friends

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Mathrandom7910** [comment] 2022-04-17 22:05
duplicate of #2054 (and may others). Read meteor's wiki https://github.com/MeteorDevelopment/meteor-client/wiki#how-do-i-use-meteor-on-older-minecraft-versions which just says to use viafabric 1.18.2

**Closed** 2022-04-18 12:16 UTC
Labels: enhancement
