### ISSUE TITLE
MultiTask Module

### ISSUE THREAD

**Issue by Joao0464** [MeteorDevelopment/meteor-client#3668] opened 2023-05-18 22:25 UTC
### Describe the feature

Add MultiTask module who allows to mine blocks atack enemies when holding shield, eating food, pulling bow etc such when you holding shield you can eat golden apple.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment] 2023-07-06 07:08
Duplicate of #3336

**Closed** 2023-07-11 03:34 UTC
Labels: enhancement
