### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Nix596** [MeteorDevelopment/meteor-client#1465] opened 2021-09-04 16:56 UTC
### Describe the bug

I am using meteor with voxel map mod and after closing map I cant see mods I turned on

### Steps to reproduce

```bash
1.Open map fullscreen
2.close map
3.and voila
...
```

### Meteor Version

meteor client v0.4.6 build #1241

### Minecraft Version

1.17.1

### Operating System

Windows

**Comment by MineGame159** [comment] 2021-09-04 16:57
Duplicate of #1201

**Closed by MineGame159** 2021-09-04 16:57 UTC
Labels: bug
