### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RxJvc** [MeteorDevelopment/meteor-client#4132] opened 2023-10-12 02:06 UTC
### Describe the bug

Kicks me from server once I join a different instance/gamemode in that server telling me to turn off my recording software or update my graphics driver even though it is updated and my recording software is off

### Steps to reproduce

```bash
1.Use meteor client
2.Join a server
3.Click on NPC (one that loads you into a gamemode)
4.Loading screen comes up and I crash
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/lSmhEN2

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ManInMyVan** [comment] 2023-10-12 04:07
Try disabling any enabled modules

**Comment by Fiz-Victor** [comment] 2023-10-12 17:52
Duplicate of #4127

**Closed** 2023-10-13 21:33 UTC
Labels: bug
