### ISSUE TITLE
[Suggestion] Ore sim module

### ISSUE THREAD

**Issue by Anfeket** [MeteorDevelopment/meteor-client#1405] opened 2021-08-24 23:01 UTC
**Describe the feature**
Simulating ores using seeds, practically bypassing ore obfuscation.

**Additional info**
Can be used in Atomic client.

**Comment by mathmakgakpak** [comment] 2021-08-25 08:09
duplicate of https://github.com/MeteorDevelopment/meteor-client/issues/537

**Comment by RedCarlos26** [comment] 2021-09-01 14:53
@seasnail8169

**Closed** 2021-09-01 22:22 UTC
Labels: enhancement
