### ISSUE TITLE
[Suggestion] Language Support?

### ISSUE THREAD

**Issue by PointsGoPro** [MeteorDevelopment/meteor-client#2342] opened 2022-06-03 11:10 UTC
### Describe the feature

Hello, in short, I would like that in the Meteor client you could see Russian characters or other characters that are simply not displayed in the Meteor
![Wait](https://user-images.githubusercontent.com/43149325/171842868-da0d65bf-2bc0-4886-81c1-f38d58e7bb71.png)
but or suggest that the Meteor client does not change its language depending on which one you have in minecraft.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment] 2022-06-03 11:11
Not possible beacuse of the font used by Meteor.
You'd need to provide a .ttf font capable of displaying characters for Russian, Chinese and other non-latin languages.

**Comment by MineGame159** [comment] 2022-06-03 20:24
> Not possible beacuse of the font used by Meteor. You'd need to provide a .ttf font capable of displaying characters for Russian, Chinese and other non-latin languages.

Not true.


Duplicate of #333.

**Closed by MineGame159** 2022-06-03 20:24 UTC
Labels: enhancement

**Comment by DarkFenix139** [comment] 2023-03-13 10:34
Нужно просто зайти в настройки Meteor и отключить кастомный шрифт. И тогда все русские символы будут отображаться.
>>>
You just need to go to the Meteor settings and disable the custom font. And then all Russian characters will be displayed.
