### ISSUE TITLE
[Suggestion] Add Auto mine 

### ISSUE THREAD

**Issue by Manksui** [MeteorDevelopment/meteor-client#1377] opened 2021-08-16 03:33 UTC
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by StormyBytes** [comment] 2021-08-16 03:38
duplicate of #1269 
check if your suggestion was already submitted prior to submitting a new issue.

**Comment by PiotrekUnityDeveloper** [comment] 2021-08-16 10:54
just enable autoclicker on Hold mode lol

**Closed** 2021-08-17 12:20 UTC
Labels: enhancement
