### ISSUE TITLE
[Bug] meteor crash with mods

### ISSUE THREAD

**Issue by EddieOngh** [MeteorDevelopment/meteor-client#4486] opened 2024-03-28 15:16 UTC
### Describe the bug

so i downloaded some cpvp mods but when i tried launching minecraft and entering a world it crashed instantly giving me an error code saying a video capturing app may cause it and i should delete it. i have obs installed and the amd gpu app any help?

### Steps to reproduce

1 i downloaded these mods
![image](https://github.com/MeteorDevelopment/meteor-client/assets/159192984/dc3ba123-67a7-4ee4-a586-2c6f54c9189a)
then i launched minecraft and it crashed
2 i deleted the morechathistory mod and minecraft launched but it crashed when i tried getting into a world
3 it gave me this error ^Maybe the problem is in the program you once installed. This program captures video from your desktop. Uninstall a program with this functionality to resolve the problem^

crash log https://mclo.gs/YFFlKJs

### Meteor Version

0.55

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment] 2024-03-28 15:19
1. Crashes should use the dedicated crash issue template.
2. Crashes should come with a log uploaded to https://mclo.gs/ as specified in our FAQ.

Please do as requested if you intend to get help.

**Comment by Big-Iron-Cheems** [comment] 2024-03-28 15:44
You're using Meteor for 1.20.2, so use Sodium 0.5.3 instead of 0.5.5 and it should work.
Duplicate of many similar issues.

**Closed by Big-Iron-Cheems** 2024-03-28 15:44 UTC
Labels: bug
