### ISSUE TITLE
[Suggestion] A Meteor IRC Chat Module

### ISSUE THREAD

**Issue by BookWyrm114** [MeteorDevelopment/meteor-client#3372] opened 2023-02-23 21:26 UTC
### Describe the feature

It would be great to have an IRC for all meteor users, probably most wouldn't use it, but for those who would, it would be really useful for easily getting help with meteor, or with doing stuff on servers, especially for people who don't have discord or don't want to constantly pause minecraft and chat in external apps. Even if you don't run an official IRC (though that would be preferable), an IRC module with a customizable prefix for using IRC chat could be useful, that way people could host their own private IRC servers and input the information into the module's config, which would also be a great feature even if there's an official IRC.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by DesiCow** [comment] 2023-02-24 00:43
Duplicate of #2180

**Comment by BookWyrm114** [comment] 2023-02-24 01:16
oh, sorry, I didn't notice there was already a suggestion for one, however could this suggestion remain open because it goes into more detail about the suggestion than #2180, and the title is much more self-explanatory.

**Comment by Hellinduction** [comment] 2023-03-15 10:56
I would also want to see this

**Comment by Ompyl** [comment] 2023-03-17 07:09
Me too

**Comment by I-Got-You-Dead2** [comment] 2023-03-17 11:58
Honestly go die

**Comment by Hellinduction** [comment] 2023-03-17 18:56
> Honestly go die

Nice to see how polite and welcoming this community is. Something tells me you are such a delightful, friendly person to be around and would just love to meet someone like you. Everyone should aspire to be just like you.

**Comment by I-Got-You-Dead2** [comment] 2023-03-18 00:05
It has already been said multiple time that irc will NEVER be added to meteor so people need to stop making issues

> > Honestly go die
> 
> Nice to see how polite and welcoming this community is. Something tells me you are such a delightful, friendly person to be around and would just love to meet someone like you. Everyone should aspire to be just like you.

**Closed** 2023-03-18 15:57 UTC
Labels: enhancement
