### ISSUE TITLE
Editing your HUD whilst not being ingame crashes

### ISSUE THREAD

**Issue by DAMcraft** [MeteorDevelopment/meteor-client#3154] opened 2023-01-05 16:29 UTC
### Describe the bug

Trying to edit HUD whilst not being in-game (for example via pressing your GUI button in the server selection screen and selecting "HUD" in the top-bar) will crash your game 

### Steps to reproduce

```bash
1. Open server selection screen
2. Open your GUI using keybind
3. Press on HUD at the top
4. profit or something idk
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment] 2023-01-05 17:09
post a crash report

**Comment by Big-Iron-Cheems** [comment] 2023-01-28 15:22
Marked as incomplete until a related crash report is provided.
Also, cannot reproduce this issue on the latest dev-build (v1757 at the time of writing).

**Closed by Big-Iron-Cheems** 2023-01-28 15:22 UTC
Labels: bug, incomplete
