### ISSUE TITLE
[Bug] Trajectories does not predict over blocks

### ISSUE THREAD

**Issue by SylveonBottle** [MeteorDevelopment/meteor-client#298] opened 2021-03-13 03:40 UTC
**Describe the bug**
You can't shoot over blocks.

**To Reproduce**
1. enable trajectories
2. aim over a block
3. note how trajectories has autism
![javaw_ntdbH7aLoT](https://user-images.githubusercontent.com/17802843/111017810-66ab1100-83ad-11eb-9bd1-fa6519606a02.png)

the enderpearl should totally land over the nether block.

**Expected behavior**

something like this
![Untitled](https://user-images.githubusercontent.com/17802843/111017857-b7bb0500-83ad-11eb-941b-b7e3508c4236.png)

**Additional context**

if you fix this, don't path infinitely into the void. it'll cause crash

**Comment by RedCarlos26** [comment] 2021-03-14 05:16
I can reproduce this bug. Your fix seems great, and the fact to not predict it indefinitely is real week thinked.

**Comment by StormyBytes** [comment] 2021-03-23 23:20
There seems to be a bug with the predicted landing spot .
The path prediction works normally, but the landing spot prediction is buggy.

Here are some images taken using freecam.
(Orange line is the path prediction, and the orange square is the landing spot prediction)
![2021-03-23_08 56 29](https://user-images.githubusercontent.com/72693226/112230845-32b2d400-8c68-11eb-9496-1566354188e1.png)
![2021-03-23_08 57 13](https://user-images.githubusercontent.com/72693226/112230880-43634a00-8c68-11eb-80bb-8a4b79e58261.png)

Here it shows that the path prediction is predicting the correct path (arrow is moving along the predicted path), but the predicted land spot is false. (arrow does not land on the predicted landing spot)
![2021-03-23_08 57 41](https://user-images.githubusercontent.com/72693226/112230915-52e29300-8c68-11eb-98d2-474737bb4e1f.png)

**Comment by SylveonBottle** [comment] 2021-03-24 00:13
I'll also add that with my testing I have found the predicting path for
fishingrod to be highly inaccurate when looking down.
However, since one issue can be fixed without the other, I'd like to
suggest making a separate bug for the inaccuracies of prediction. This bug
report can be strictly about being able to see where the rod lands without
any blocks obscuring the line, as seen in my original image.

**Comment by RedCarlos26** [comment] 2021-03-25 02:18
> I'll also add that with my testing I have found the predicting path for
> fishingrod to be highly inaccurate when looking down.
> However, since one issue can be fixed without the other, I'd like to
> suggest making a separate bug for the inaccuracies of prediction. This bug
> report can be strictly about being able to see where the rod lands without
> any blocks obscuring the line, as seen in my original image.
> 

I have a bug report for this,I can modify it with the other trajectories that are wrong.

**Comment by MineGame159** [comment] 2021-04-21 16:56
Fixed in 5fe1d3e4276e63df195d2d2fd6ecb97dfb76e6ec

**Closed by MineGame159** 2021-04-21 16:56 UTC
Labels: bug
