### ISSUE TITLE
Nametag item rendering problem 

### ISSUE THREAD

**Issue by PFTpancake** [MeteorDevelopment/meteor-client#3761] opened 2023-06-22 00:38 UTC
### Describe the bug

Not using meteors custom font option  fucks nametags 

### Steps to reproduce

```bash
turn on nametags and turn off custom font
```

### Meteor Version

meteor client v0.5.4 build #1857

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment] 2023-06-22 11:28
show screenshots

**Comment by RacoonDog** [comment] 2023-06-24 19:46
> NameTags have rendering problem
> ![2023-06-22_17 32 19](https://user-images.githubusercontent.com/59806025/247964056-3b41460b-5286-4deb-8c38-ed895c7e55f8.png)

looks good to me, what exactly is the issue?

**Comment by orexot** [comment] 2023-06-24 23:11
> > NameTags have rendering problem
> > ![2023-06-22_17 32 19](https://user-images.githubusercontent.com/59806025/247964056-3b41460b-5286-4deb-8c38-ed895c7e55f8.png)
> 
> looks good to me, what exactly is the issue?

Opposite positioning of armor and nickname
<img width="488" alt="Снимок экрана 2023-06-25 015538" src="https://github.com/MeteorDevelopment/meteor-client/assets/59806025/fdb3bdff-7f08-4770-8bbb-87806c7c6c39">

**Comment by ManInMyVan** [comment] 2023-06-25 04:58
Yeah this is kinda annoying

**Comment by BDARmech** [comment] 2023-06-25 15:29
Very annoying. But beautiful chaos.


On Jun 25, 2023, at 12:58 AM, ManInMyVan ***@***.***> wrote:

﻿

Yeah this is kinda annoying

**Comment by ManInMyVan** [comment] 2023-07-06 06:48
Also duplicate of #3728

**Comment by MineGame159** [comment] 2024-07-16 13:51
Not enough info

**Closed by MineGame159** 2024-07-16 13:51 UTC
Labels: bug
