### ISSUE TITLE
[Suggestion] Tracer Thiccness adjustable

### ISSUE THREAD

**Issue by Tokara1** [MeteorDevelopment/meteor-client#998] opened 2021-06-09 09:59 UTC
**Describe the feature**
Make tracer thiccness adjustable bc in some cases the Thin tracers are hard to Spot 
( Dynamic, adjustable With slidebar )

**Screenshots**
N/A

**Additional info**
N/A

**Comment by StormyBytes** [comment] 2021-06-09 14:23
Duplicate of #521

**Comment by Tokara1** [comment] 2021-06-09 15:05
Oopsy

**Closed** 2021-06-20 15:33 UTC
Labels: enhancement
