### ISSUE TITLE
[Bug]  My x-ray wont worrk

### ISSUE THREAD

**Issue by DankAssassin** [MeteorDevelopment/meteor-client#2288] opened 2022-05-14 04:34 UTC
### Describe the bug

![Minecraft_ 1 18 2 - Multiplayer (3rd-party Server) 5_13_2022 9_30_24 PM](https://user-images.githubusercontent.com/105532783/168410699-893560b1-1b6f-402e-9c93-663de4dd2b3a.png)
this is how it looks like when i turn on x ray (idk if the screen shot went through or not) but it just looks like if i had my settings on the lowest and idk why

### Steps to reproduce

```bash
i dont know
```

### Meteor Version

1.18.2

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotAstralYT** [comment] 2022-05-14 05:46
opacity 100% be liek

**Comment by Tomxdhd** [comment] 2022-05-14 14:16
> opacity 100% be liek

On the latest dev build the xray also isn't working for me so it's not 100% opacity

**Comment by Wide-Cat** [comment] 2022-05-14 18:56
What other mods are you using?

**Comment by DankAssassin** [comment] 2022-05-14 19:51
> What other mods are you using?

im using seed cracker

**Comment by Mathrandom7910** [comment] 2022-05-14 21:08
duplicate of #2280

**Closed** 2022-05-14 22:37 UTC
Labels: bug

**Comment by DankAssassin** [comment] 2022-05-15 03:20
bru
