### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by a-couple-objects** [MeteorDevelopment/meteor-client#836] opened 2021-05-25 15:14 UTC
**Describe the feature**
An option for Nuker that right-clicks blocks instead of breaking them

**Comment by flaxeneel2** [comment] 2021-05-25 15:58
hm, but what will it even be useful for lol, i mean it's just a simple addition (in theory) but like what will you do with it? build like a circle around you or smth and stop? doesn't sound too useful does it?

**Comment by a-couple-objects** [comment] 2021-05-26 06:37
> hm, but what will it even be useful for lol, i mean it's just a simple addition (in theory) but like what will you do with it? build like a circle around you or smth and stop? doesn't sound too useful does it?

like right click TNT or remove lava and water without blocks

**Comment by seasnail8169** [comment] 2021-05-26 15:56
duplicate of #744

**Closed by seasnail8169** 2021-05-26 15:56 UTC
Labels: enhancement
