### ISSUE TITLE
auto highway builder

### ISSUE THREAD

**Issue by mohamadbagherblack** [MeteorDevelopment/meteor-client#962] opened 2021-06-06 20:29 UTC
hello
please add auto highway builder like kami blue highway tools like this video ->
https://www.youtube.com/watch?v=rwkDk_Xn2Y4&t=3s
meteor has anything we need so please add this too
anarchy players really need this

**Comment by StormyBytes** [comment] 2021-06-06 23:22
Duplicate of #516

**Comment by RedCarlos26** [comment] 2021-06-07 02:58
@seasnail8169

**Closed** 2021-06-07 08:06 UTC
Labels: enhancement
