### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Bao-Boy** [MeteorDevelopment/meteor-client#2373] opened 2022-06-12 23:19 UTC
### Describe the bug

X-ray doesn't seem to be working

### Steps to reproduce

```bash
I have no idea it just happend
```

### Meteor Version

Dev Build 0.5.0 - 1494

### Minecraft Version

1.18.2 and 1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Starmania** [comment] 2022-06-13 07:05
Duplicate of #2240

**Closed** 2022-06-13 20:31 UTC
Labels: bug
