### ISSUE TITLE
[Bug] Hud editor not rendering hud elements

### ISSUE THREAD

**Issue by Samreds** [MeteorDevelopment/meteor-client#771] opened 2021-05-18 16:06 UTC
**Describe the bug**
Hud selector/editor is messed up on latest build 

**To Reproduce**
1. Go to 'gui for meteor'
2. Click on 'hud'
3. Hud editor will be invisible 

**Expected behavior**
The hud editor is supposed to appear with text 

**Screenshots**
![image](https://user-images.githubusercontent.com/65549785/118685839-0d09fd00-b7c9-11eb-90ea-7d3cff0069ef.png)

**Additional context**
Dev build 875

**Comment by C10udburst** [comment] 2021-05-18 16:37
Do you have the HUD module enabled?

**Comment by RedCarlos26** [comment] 2021-05-18 17:05
I cannot reproduce

**Comment by MineGame159** [comment] 2021-06-22 11:41
Fixed in c5915d6cc62fbea6cddca81c9a45818d3392c4fa

**Closed by MineGame159** 2021-06-22 11:41 UTC
Labels: bug
