### ISSUE TITLE
[Suggestion] custom font or fix language display error

### ISSUE THREAD

**Issue by RouZong** [MeteorDevelopment/meteor-client#1524] opened 2021-09-20 00:59 UTC
### Describe the feature

my language  is chinese,then some funtion words is miss
![image](https://user-images.githubusercontent.com/6872828/133948873-f22774d6-44fd-49ff-abde-7b0711e7e4ec.png)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by JaanDev** [comment] 2021-09-21 16:09
Yeah same problem, but I am Russian. I don't really like the fact that I have to switch language to English to add something to xray, kill aura etc. Also, I've checked that the fonts are not the problem. I'm using Comfortaa and you can clearly see that it has all the Russian letters.

![image](https://user-images.githubusercontent.com/67502867/134206832-06a371de-124a-4f5d-9b52-76505fea8926.png)

This bug is very annoying, devs, fix it please!

P.S. Oh, and a possibility to localize the client would also be very cool! :D

**Comment by RouZong** [comment] 2021-09-22 04:25
> 是的，同樣的問題，但我是俄羅斯人。我真的不喜歡我必須將語言切換為英語才能向 xray、kill aura 等添加內容的事實。此外，我已經檢查過字體不是問題。我正在使用 Comfortaa，您可以清楚地看到它包含所有俄語字母。
> 
> ![圖片](https://user-images.githubusercontent.com/67502867/134206832-06a371de-124a-4f5d-9b52-76505fea8926.png)
> 
> 這個錯誤很煩人，開發者，請修復它！
> 
> PS 哦，本地化客戶端的可能性也很酷！:D

You can use your language to search but it is Invisible XDD

**Comment by JaanDev** [comment] 2021-09-22 09:06
Yeah i know lol

**Comment by MineGame159** [comment] 2021-09-30 14:39
Duplicate of #333.

**Closed by MineGame159** 2021-09-30 14:39 UTC
Labels: enhancement
