### ISSUE TITLE
[Bug] Xray not working

### ISSUE THREAD

**Issue by theRealK2346** [MeteorDevelopment/meteor-client#2359] opened 2022-06-10 22:39 UTC
### Describe the bug

The xray for 4.9 is not working for some reason could you please fix it?

### Steps to reproduce

```bash
You activate xray
```

### Meteor Version

4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Starmania** [comment] 2022-06-12 09:11
![2022-06-12_11 07 59](https://user-images.githubusercontent.com/52313983/173225978-3d7eb4c9-7b46-4181-ac21-cdc994b765c6.png)
![2022-06-12_11 07 46](https://user-images.githubusercontent.com/52313983/173225982-3dbbb28d-a77c-4061-a35c-364e83b85f94.png)
Reproductible on lasted dev ([ee767ac](https://github.com/MeteorDevelopment/meteor-client/commit/ee767ac9a8adcf53e0b9224d1030c83337726a18)). Not impacted by `Graphics: Fabulous!`

**Comment by Starmania** [comment] 2022-06-13 07:07
Also duplicate of #2240

**Closed** 2022-06-13 20:33 UTC
Labels: bug
