### ISSUE TITLE
渲染器

### ISSUE THREAD

**Issue by weizhon** [MeteorDevelopment/meteor-client#4826] opened 2024-08-12 14:14 UTC
### Describe the feature

Can you adapt to vulkan mod

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment] 2024-08-12 14:15
Duplicate of #3567

**Closed by MineGame159** 2024-08-12 14:15 UTC
Labels: enhancement
