### ISSUE TITLE
[Bug] Crash with REI (Roughly Enough Items for Fabric)

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [MeteorDevelopment/meteor-client#988] opened 2021-06-08 03:12 UTC
When searching for items in REI, the game crashed, saving the world and exiting the instance.

Crash report:
`---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/7/21 11:07 PM
Description: Unexpected error

java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at me.shedaniel.rei.api.ClientHelper.appendModIdToTooltips(ClientHelper.java:197)
	at me.shedaniel.rei.impl.ItemEntryStack.getTooltip(ItemEntryStack.java:292)
	at me.shedaniel.rei.impl.SearchArgument.tryGetEntryStackTooltip(SearchArgument.java:207)
	at me.shedaniel.rei.impl.search.TooltipArgument.matches(TooltipArgument.java:71)
	at me.shedaniel.rei.impl.search.TooltipArgument.matches(TooltipArgument.java:42)
	at me.shedaniel.rei.impl.SearchArgument.matches(SearchArgument.java:203)
	at me.shedaniel.rei.impl.SearchArgument.matches(SearchArgument.java:194)
	at me.shedaniel.rei.impl.SearchArgument.canSearchTermsBeAppliedTo(SearchArgument.java:178)
	at me.shedaniel.rei.gui.widget.EntryListWidget.canLastSearchTermsBeAppliedTo(EntryListWidget.java:559)
	at me.shedaniel.rei.gui.widget.EntryListWidget.lambda$updateSearch$6(EntryListWidget.java:511)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)

-- Affected level --
Details:
	All players: 1 total; [class_746['TheGreatCatAdorer'/2, l='ClientLevel', x=21.63, y=3.00, z=3.47]]
	Chunk stats: SodiumChunkCache: 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (-56,2,-120), Chunk: (at 8,0,8 in -4,-8; contains blocks -64,0,-128 to -49,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 310418 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 220703696 bytes (210 MB) / 671690752 bytes (640 MB) up to 2112618496 bytes (2014 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.3.1
		baritone: Baritone 1.6.3
		betterbeds: Better Beds 1.1.0
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterf3: BetterF3 1.1.3
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		bewitchment: Bewitchment 1.16.5-15
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		carpet: Carpet Mod 1.4.38
		carpet-extra: Carpet Extra 1.4.34
		carvedmelons: Carved Melons 1.2.3
		charm: Charm 2.3.2
		chime: Chime 1.1.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		enchant_giver: Enchant Giver 1.0.3
		fabric: Fabric API 0.34.6+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabrication: Fabrication 1.3.4
		fabricloader: Fabric Loader 0.11.3
		ferritecore: FerriteCore 2.0.4
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		flytre_lib: FlytreLib 0.2.11
		geckolib3: Geckolib 3.0.36
		hydrogen: Hydrogen 0.2
		illuminations: Illuminations 1.5.1
		impersonate: Impersonate 2.2.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lazydfu: LazyDFU 0.1.2
		litematica: Litematica 0.0.0-dev.20210120.213004
		lithium: Lithium 0.6.4
		locki: Locki 0.2.0
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		mcda: MC Dungeons Armors 1.4.5
		mcdar: MC Dungeons Artifacts 1.1.3
		mcdw: MC Dungeons Weapons 3.2.0
		meteor-client: Meteor Client 0.4.4
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.9
		overworld_two: Overworld 2 1.0.4
		patchouli: Patchouli 1.16.4-51-FABRIC
		pehkui: Pehkui 2.2.0+21w20a
		playerabilitylib: Pal 1.2.2
		pride: Pride Lib 1.0.0+1.16
		quilt-loading-screen: Quilt Loading Screen 1.2.3+1.16.5
		rangers_haven: Ranger's Haven 2.2.1
		ratsmischief: Rat's Mischief 1.1.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.11.2-fabric
		requiem: Requiem 1.7.11
		requiemapi: Requiem-API 1.7.11
		roughlyenoughitems: Roughly Enough Items 5.12.235
		roughlyenoughitems-api: REI (API) 5.12.235
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.235
		roughlyenoughitems-runtime: REI (Runtime) 5.12.235
		roughlyenoughresources: Roughly Enough Resources 2.1.4
		satin: Satin 1.5.1
		sodium: Sodium 0.1.1
		somnus: Somnus API 0.0.11-1.16.5
		spellbound: Spellbound 1.3.0
		staffofbuilding: Staff of Building 1.2.6-1.16.5
		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		trinkets: Trinkets 2.6.7
		tweakeroo: Tweakeroo 0.10.0-dev.20210303.123654
		voyager: Voyager 1.0.0
		xaerominimap: Xaero's Minimap 21.9.0.1
		xaeroworldmap: Xaero's World Map 1.14.1
		yungsapi: YUNG's API 1.16.5-Fabric-5
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 605 GL version 4.6.0 - Build 27.20.100.8681, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/VanillaTweaks_r127178.zip, Fabric Mods, betterbeds/fancybeds
	Current Language: English (US)
	CPU: 4x Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz

-- Meteor Client --
Version: 0.4.4

[Player]:
Portals (portals)

[Render]:
Better Tooltips (better-tooltips)
Break Indicators (break-indicators)
HUD (HUD)
Item Physics (item-physics)
Unfocused Cpu (unfocused-cpu)

[World]:
Ambience (ambience)
Auto Breed (auto-breed)
Enderman Look (enderman-look)

[Misc]:
Better Chat (better-chat)
Better Tab (better-tab)
Inventory Tweaks (inventory-tweaks)`

**Comment by TheGreatCatAdorer** [comment] 2021-06-08 03:22
I just tested with the latest version of REI on CurseForge; the crash still occurs.

**Comment by bartaback** [comment] 2021-06-08 09:27
Same as #432 
It's some Better Tooltips module options from Meteor (not Shulker peek)

**Comment by MineGame159** [comment] 2021-06-22 12:15
Duplicate of #432

**Closed by MineGame159** 2021-06-22 12:15 UTC
Labels: bug
