### ISSUE TITLE
[Suggestion] The interface does not support simplified Chinese and traditional Chinese?

### ISSUE THREAD

**Issue by 1023959388** [MeteorDevelopment/meteor-client#2674] opened 2022-08-18 12:15 UTC
### Describe the feature

I am modifying the interface to simplified Chinese or traditional Chinese. The interface in the game is only blank!
Hope to support simplified Chinese and traditional Chinese！

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by 1023959388** [comment] 2022-08-18 12:22
I modify it here

**Comment by 1023959388** [comment] 2022-08-18 12:23
![T0WQ2(Y$) 7CLG%$_9NI}R8](https://user-images.githubusercontent.com/88093688/185393833-10c7d72a-9091-4411-a1e1-a72b4ce88b59.png)

**Comment by 1023959388** [comment] 2022-08-18 12:24
![image](https://user-images.githubusercontent.com/88093688/185393903-68f41e29-0052-4a14-99ce-9ccaf2b6cb8c.png)

**Comment by MineGame159** [comment] 2022-09-01 18:14
Duplicate of #333.

**Closed by MineGame159** 2022-09-01 18:14 UTC
Labels: enhancement
