### ISSUE TITLE
[Suggestion] Make zoom not make waypoints smaller

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1394] opened 2021-08-21 09:18 UTC
**Describe the feature**
Make zoom not make waypoints smaller. When you zoom in, waypoints and nametags remain the same size despite everything else zooming in.

**Comment by tyrannus00** [comment] 2021-08-21 23:46
This happens with any zoom mod btw, so it's not a zoom issue

**Comment by RedCarlos26** [comment] 2021-09-01 13:35
Duplicate of #1150

**Comment by RedCarlos26** [comment] 2021-09-07 04:58
@seasnail8169 ^

**Closed** 2021-09-07 23:55 UTC
Labels: enhancement
