### ISSUE TITLE
I still receive fall damage when landing from fly, even with nofall on.

### ISSUE THREAD

**Issue by Spicymang04** [MeteorDevelopment/meteor-client#1110] opened 2021-06-24 03:57 UTC
**Describe the bug**
When flying (even with nofall) when trying to land you take damage when not landing in water or the sort.

**To Reproduce**
1. Fly around in survival and try to land.

**Expected behavior**
You will take damage and without armor you will most likely die.

**Screenshots**

**Additional context**
Meteor 4.4 1108
Litematica

**Comment by NightMite** [comment] 2021-06-27 15:53
This happens on a server or on singleplayer?

**Comment by D3V1LC0D3R** [comment] 2021-07-17 15:32
seems like a duplicate of #1097

**Closed** 2021-07-27 14:08 UTC
Labels: bug
