### ISSUE TITLE
AutoReconnect reconnects to the wrong server

### ISSUE THREAD

**Issue by theotherhades** [MeteorDevelopment/meteor-client#3866] opened 2023-07-22 08:58 UTC
### Describe the bug

When disconnected from a server with AutoReconnect enabled, the client is reconnected to the wrong server. In the linked video I am disconnected from Constantiam and when AutoReconnect triggers I am instead sent to 2b2t.

Expected behavior: I am reconnected to Constantiam.

Observed behavior: when disconnected from Constantiam I am reconnected to 2b2t.

Link to video: https://youtu.be/OaC7KY-zALY

### Steps to reproduce

```bash
1. Get disconnected from a server
2. Wait for AutoReconnect to kick in
```

### Meteor Version

0.5.4 1857

### Minecraft Version

1.20.1 (using ViaFabricPlus to connect to 1.19.4)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ManInMyVan** [comment] 2023-07-22 09:46
> This bug wasn't already reported (I have searched bug reports on GitHub).

Are you sure about that?

Duplicate of #3788

**Comment by Nova-Squ1** [comment] 2023-07-22 10:57
I have met similar bugs

**Comment by theotherhades** [comment] 2023-07-22 11:28
> > This bug wasn't already reported (I have searched bug reports on GitHub).
> 
> Are you sure about that?
> 
> Duplicate of #3788

Ah, my bad, I searched issues for "auto reconnect" not "reconnect"

**Closed** 2023-07-22 11:28 UTC
Labels: bug
