### ISSUE TITLE
[Suggestion] Where can i find the 1.21 build ?

### ISSUE THREAD

**Issue by Mal1koRe1ss** [MeteorDevelopment/meteor-client#4852] opened 2024-08-22 09:31 UTC
### Describe the feature

I searched up the discord builded some versions but i didn't find any 1.21. There was an link for 1.21 Meteor Client but that doesn't works in 1.21 it works in 1.21.1 can anybody help me ?
![image](https://github.com/user-attachments/assets/ed2da2b3-c8b1-4654-b142-72bf126cc5ce)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by zaBees** [comment] 2024-08-22 09:36
click the clock check where it says updated to 1.21.1 and go before that, then build it

**Comment by Mal1koRe1ss** [comment] 2024-08-22 09:38
Ok i'm gonna try this thx

**Comment by Mal1koRe1ss** [comment] 2024-08-22 09:43
Same

**Comment by Mal1koRe1ss** [comment] 2024-08-22 09:47
I try to find the older build with web archive but it just shows me a blank page

**Comment by Mal1koRe1ss** [comment] 2024-08-22 09:52
I found a build but it give's me this error

[12:51:18] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.16.2
[12:51:18] [ForkJoinPool-1-worker-4/WARN]: Mod modid uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:51:18] [main/INFO]: Loading 70 mods:
	- baritone-meteor 1.21-SNAPSHOT
	   \-- dev_babbaj_nether-pathfinder 1.4.1
	- fabric-api 0.102.0+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.68+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.16+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.19+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.5.0+c5e2b5c6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.27+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.16+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae06d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.4+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df360d1
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.2+60c3209bd1
	   |-- fabric-object-builder-api-v1 15.2.0+a551f7a4d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.12+65089712d1
	   |-- fabric-registry-sync-v0 5.1.2+60c3209bd1
	   |-- fabric-renderer-api-v1 3.4.0+c705a49cd1
	   |-- fabric-renderer-indigo 1.7.0+c705a49cd1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b1d1
	   |-- fabric-resource-loader-v0 1.3.0+56599129d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.86+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.16+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.1.0+176f9036d1
	- fabricloader 0.16.2
	   \-- mixinextras 0.4.1
	- indium 1.0.35+mc1.21
	- java 21
	- lithium 0.13.0
	- meteor-client 0.5.8-2147
	- minecraft 1.21
	- modid ${version}
	   \-- javazoom_jlayer 1.0.1
	- modmenu 11.0.1
	   \-- placeholder-api 2.4.0-pre.2+1.21
	- numbyhack 2.3
	- nvidium 0.2.9-beta
	- reeses-sodium-options 1.7.3+mc1.21
	- sigma-utils 0.1.10-alpha
	- sodium 0.5.11+mc1.21
	- sodium-extra 0.5.7+mc1.21
	   \-- caffeineconfig 1.3.0+1.17
	- thunderhack 1.7
[12:51:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/Mal1koRe1ss/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.2+mixin.0.8.7/sponge-mixin-0.15.2+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[12:51:19] [main/INFO]: Compatibility level set to JAVA_17
[12:51:19] [main/INFO]: Compatibility level set to JAVA_21
[12:51:19] [main/INFO]: Loaded configuration file for Lithium: 144 options available, 0 override(s) found
[12:51:20] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[12:51:20] [main/INFO]: Loaded configuration file for Sodium Extra: 35 options available, 0 override(s) found
[12:51:22] [main/INFO]: Searching for graphics cards...
[12:51:22] [main/INFO]: Found graphics adapter: AdapterInfo{vendor=NVIDIA, description='NVIDIA GeForce RTX 2060', adapterType=0x0000030B, openglIcdFilePath='C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1196b342b24df5d1\nvoglv64.dll', openglIcdVersion=32.0.15.6070}
[12:51:23] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[12:51:23] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[12:51:23] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[12:51:26] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 732 milliseconds
[12:51:36] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[12:51:36] [Render thread/INFO]: Setting user: Mal1koRe1ss
[12:51:38] [Render thread/INFO]: Starting addon initialization.
[12:51:38] [Render thread/INFO]: Initializing addon: com.example.ExampleMod
[12:51:38] [Render thread/INFO]: I simply bypass
[12:51:38] [Render thread/INFO]: Addon initialized successfully: com.example.ExampleMod
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.Other.Radio
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.Other.Radio
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.VulcanBypasses.VulcanSpeed
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.VulcanBypasses.VulcanSpeed
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.VulcanBypasses.VulcanBoatFly
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.VulcanBypasses.VulcanBoatFly
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.VulcanBypasses.VulcanBoatFly2
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.VulcanBypasses.VulcanBoatFly2
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.VulcanBypasses.VulcanNofall
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.VulcanBypasses.VulcanNofall
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.VulcanBypasses.VulcanVelocity
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.VulcanBypasses.VulcanVelocity
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.VulcanBypasses.VulcanGlide
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.VulcanBypasses.VulcanGlide
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.VulcanBypasses.PacketFly
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.VulcanBypasses.PacketFly
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.Other.PingSpoof
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.Other.PingSpoof
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.Other.AAC1910
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.Other.AAC1910
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.Other.VerusCombat
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.Other.VerusCombat
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.Other.BedFuckerButWithoutPacket
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.Other.BedFuckerButWithoutPacket
[12:51:38] [Render thread/INFO]: Registering module: com.example.modules.VulcanBypasses.VulcanSpider
[12:51:38] [Render thread/INFO]: Module registered successfully: com.example.modules.VulcanBypasses.VulcanSpider
[12:51:38] [Render thread/INFO]: Registering command: com.example.commands.ExampleCommand
[12:51:38] [Render thread/INFO]: Command registered successfully: com.example.commands.ExampleCommand
[12:51:38] [Render thread/INFO]: Registering HUD element: com.example.hud.ExampleHudElement
[12:51:38] [Render thread/INFO]: HUD element registered successfully: com.example.hud.ExampleHudElement
[12:51:38] [Render thread/INFO]: Addon initialization complete.
[12:51:39] [Render thread/INFO]: [ThunderHack] Init time: 2255 ms.
[12:51:39] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[12:51:40] [Render thread/INFO]: Checking mod updates...
[12:51:40] [Render thread/INFO]: Starting Sigma Utils v0.1.10-alpha
[12:51:41] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[12:51:41] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[12:51:42] [Render thread/INFO]: All capabilities met
[12:51:42] [Render thread/INFO]: Enabling Nvidium
[12:51:43] [Render thread/ERROR]: Mixin apply for mod meteor-client failed meteor-client-indium.mixins.json:AbstractBlockRenderContextMixin from mod meteor-client -> link.infra.indium.renderer.render.AbstractBlockRenderContext: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onBufferQuad could not find any targets matching 'renderQuad(Llink/infra/indium/renderer/mesh/MutableQuadViewImpl;Z)V' in link/infra/indium/renderer/render/AbstractBlockRenderContext. Using refmap meteor-client-refmap.json [INJECT_PREPARE Applicator Phase -> meteor-client-indium.mixins.json:AbstractBlockRenderContextMixin from mod meteor-client -> Prepare Injections -> handler$boh000$meteor-client$onBufferQuad(Llink/infra/indium/renderer/mesh/MutableQuadViewImpl;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onBufferQuad could not find any targets matching 'renderQuad(Llink/infra/indium/renderer/mesh/MutableQuadViewImpl;Z)V' in link/infra/indium/renderer/render/AbstractBlockRenderContext. Using refmap meteor-client-refmap.json [INJECT_PREPARE Applicator Phase -> meteor-client-indium.mixins.json:AbstractBlockRenderContextMixin from mod meteor-client -> Prepare Injections -> handler$boh000$meteor-client$onBufferQuad(Llink/infra/indium/renderer/mesh/MutableQuadViewImpl;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:48) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) [meteor-client-0.5.8-2147.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.16.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) [?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) [?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.16.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at net.minecraft.class_778.<init>(class_778.java:38) [client-intermediary.jar:?]
	at net.minecraft.class_776.<init>(class_776.java:38) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:608) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]

**Comment by Big-Iron-Cheems** [comment] 2024-08-22 09:55
1. Open the [commit history](https://github.com/MeteorDevelopment/meteor-client/commits/master) page
2. Look for the commit named `X.Y.Z update`
![image](https://github.com/user-attachments/assets/0ebdf307-5ffa-4919-8956-9dc975873cdc)
3. Pick the one exactly before it, click the `Browse files` button in the top right
4. Click the green `Code` button to download the source
5. Build it [as instructed](https://meteorclient.com/faq/old-versions#building-from-source) on our FAQ (we don't provide help for this, you're on your own)

**Comment by Big-Iron-Cheems** [comment] 2024-08-22 09:59
> I found a build but it give's me this error

@Mal1koRe1ss 
Did you use the `.\gradlew build` command for this, or are you running the command within IntellliJ?
If it's the second case, be sure you make it use Gradle here instead of IntellliJ.
![image](https://github.com/user-attachments/assets/18deeec0-73e2-4f48-b06a-3861985ba424)

**Comment by Mal1koRe1ss** [comment] 2024-08-22 10:05
I'm using Gradlew in cmd

**Comment by Mal1koRe1ss** [comment] 2024-08-22 10:13
I get this error in the version that you send to me (compiled)

The game crashed whilst initializing game
Error: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of link.infra.indium.renderer.render.AbstractBlockRenderContext failed

**Comment by Big-Iron-Cheems** [comment] 2024-08-22 10:16
![image](https://github.com/user-attachments/assets/be7b8e04-595a-431f-bb61-126210e8ede1)
![image](https://github.com/user-attachments/assets/4acbf3a6-dc9e-4de9-a382-af3d65f2924b)
Seems like an issue on your end with Gradle string substitution, it builds correctly on my end.

As for the Mixin error you report, it is caused by an Indium update, and was fixed in 1.21.1 accordingly.
You can try and downgrade [Indium](https://modrinth.com/mod/indium/versions?gameVersion=1.21) (it should work with version 1.0.33)
![image](https://github.com/user-attachments/assets/92e35140-ec23-4964-b1ec-81ad3d6b8bfd)

**Comment by Mal1koRe1ss** [comment] 2024-08-22 10:17
It works fine without indium and lithium but i need some performance mods too thanks for the help

**Closed** 2024-08-22 11:33 UTC
Labels: enhancement

**Comment by SkyExploreWasTaken** [comment] 2024-09-27 19:11
Can someone give me the mod for 1.21 ? @Mal1koRe1ss ?
