### ISSUE TITLE
[Bug] Nuker stops Working In Creative After Entering Water

### ISSUE THREAD

**Issue by IIpho3nix** [MeteorDevelopment/meteor-client#704] opened 2021-05-09 06:54 UTC
**in a creative world [havent tried in survival yet] after entering water with nuker on and exiting it nuker stops working**

**Steps to reproduce the behavior**:
1. Go to a Creative World
2. Open Nuker
3. Enter Water (lake ocean or something)
4. after exiting nuker stops nuking blocks

**Expected behavior**
Nuker Still Works

**Additional context**
Meteor Version 0.4.3
Vannila Creative World
Mc Version 1.16.5

**Mods** : 
Lithium
Sodium
Phospor
MultiConnect
Meteor

**Here Is Me Reproducing The Issue**

https://user-images.githubusercontent.com/79083095/117639801-fe01ca00-b18c-11eb-8d60-9723ba4c7dab.mp4

**Comment by CountBleck** [comment] 2021-05-09 07:27
[I can't reproduce this.](https://dropbox.com/s/01hi3yxdqldcxo6/nuker_cannot_reproduce.mkv?dl=1)

**Comment by IIpho3nix** [comment] 2021-05-10 09:43
> [I can't reproduce this.](https://dropbox.com/s/01hi3yxdqldcxo6/nuker_cannot_reproduce.mkv?dl=1)

Updated The Issue With Me Reproducing It

**Comment by CountBleck** [comment] 2021-05-14 21:12
[I can reproduce it now.](https://dropbox.com/s/j0sxbz6hary3ofd/nuker_can_reproduce.mkv?dl=1)
I think it's because the delay is set to 0. It appears to try to break some block and won't stop, regardless of where you are.

**Comment by MineGame159** [comment] 2021-06-21 14:01
Fixed in c09ca6b3c8c67aa8076ef47dfe9160d267b7a238

**Closed by MineGame159** 2021-06-21 14:01 UTC
Labels: bug
