### ISSUE TITLE
[Bug] Shader ESP items Bug

### ISSUE THREAD

**Issue by xewoiy** [MeteorDevelopment/meteor-client#1730] opened 2021-11-29 13:15 UTC
### Describe the bug

if you enable ESP (with shader mode) and enable zoom, the players and the esp will not move, and what they have in their hands will remain in the same position of the screen.

### Steps to reproduce

```bash
1. Enable ESP with Shader mode
2. Enable Zoom
4. Look at players who have items in hand
```

### Meteor Version

v0.4.7 build #1340

### Minecraft Version

Minecraft 1.17.1 Fabric loader 0.11.7

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by xewoiy** [comment] 2021-11-29 13:17
https://user-images.githubusercontent.com/86353201/143874837-c8423a2e-a410-4fe4-bdc4-0a63850ee550.mp4

**Comment by MineGame159** [comment] 2022-01-02 13:19
Duplicate of #1259.

**Closed by MineGame159** 2022-01-02 13:19 UTC
Labels: bug
