### ISSUE TITLE
my game crashes

### ISSUE THREAD

**Issue by ericschokolade** [MeteorDevelopment/meteor-client#4734] opened 2024-07-08 18:11 UTC
### Steps to reproduce

1. i was just testing cuz i was a bit cerious and then i made so i cant see all and when i try to remove it it crashes but i have a anti crash mod 
2. idk how to remove it i reinstalled evething on meteor and stuff but nothing works

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/N19K40l

### Meteor Version

1.20.4/idk

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment] 2024-07-08 18:26
This issue is caused by Rejects not being up to date with [this](https://github.com/MeteorDevelopment/meteor-client/commit/546d0b945a98c61cafd4cd9330db3936eee286d1#) change we did.
For now, don't use Rejects, or avoid using the "hidden modules" feature.

We'll close this issue once Rejects updates accordingly.

**Comment by ericschokolade** [comment] 2024-07-09 11:09
so i have  updated to 1.21 
2. wait ima look

**Comment by ericschokolade** [comment] 2024-07-09 11:11
alr its fixed but can i somehow reset it the reject stuff?
cuz i use reject

**Comment by Big-Iron-Cheems** [comment] 2024-07-12 10:15
Try downloading Rejects for 1.21 and see if it works now: https://github.com/AntiCope/meteor-rejects/releases.
Hopefully all goes well this time with the latest dev builds.

**Closed** 2024-07-14 10:39 UTC
Labels: crash
