### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by poprostuxd** [MeteorDevelopment/meteor-client#3934] opened 2023-08-11 10:28 UTC
### Describe the bug

When i press "R" to enable killaura (better killaura) my minecraft just crashed.
btw. im using addon to meteor(metoer plus)
it was fine before, until one time when I turned on better killaura just minecraft shut down and "saving world" popped up.

### Steps to reproduce

```bash
just enable better killaura in meteor plus addon
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/yJymUNQ

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by dariusthechad** [comment] 2023-08-11 10:35
Not a meteor client issue close this

**Comment by Big-Iron-Cheems** [comment] 2023-08-11 10:40
Issue definitely caused by the addon, go and report it to the corresponding [GitHub](https://github.com/Nekiplay/MeteorPlus).

**Closed by Big-Iron-Cheems** 2023-08-11 10:40 UTC
Labels: bug
