### ISSUE TITLE
[Suggestion] iris shaders 

### ISSUE THREAD

**Issue by m-m574** [MeteorDevelopment/meteor-client#3595] opened 2023-04-22 18:53 UTC
### Describe the feature

make iris shaders work

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment] 2023-04-22 18:56
Duplicate of #3596

**Closed by Big-Iron-Cheems** 2023-04-22 18:56 UTC
Labels: enhancement
