### ISSUE TITLE
idk what bug is it

### ISSUE THREAD

**Issue by Grummiom** [MeteorDevelopment/meteor-client#4135] opened 2023-10-12 17:11 UTC
### Describe the bug

when trying to log in a server while a movement mod or some other mods enabled the client suddenly crashes.

### Steps to reproduce

```bash
install meteor 1.20.2 build 1947
join a server with airjump and/or other movement mods enabled (try joining og-network.net for example)
the client crashes Apon joining.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/xYApbjI

### Meteor Version

0.5.5-1947

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Fiz-Victor** [comment] 2023-10-12 17:52
Duplicate of #4127

**Closed** 2023-10-13 21:33 UTC
Labels: bug
