### ISSUE TITLE
[Suggestion] Phasing etc

### ISSUE THREAD

**Issue by dxzv666** [MeteorDevelopment/meteor-client#1997] opened 2022-01-29 11:27 UTC
### Describe the feature

I would really like to see a Phase/Noclip module on Meteor to phase into players bases

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by bluepanee** [comment] 2022-01-30 12:41
Duplicate of #1681

**Comment by Justgamer101** [comment] 2022-01-31 22:04
vclip doesn't work on vanilla. also just break 2 blocks 😆

**Comment by bluepanee** [comment] 2022-02-01 14:20
> vclip doesn't work on vanilla. also just break 2 blocks lmao

You mean hclip but who cares. vclip still a thing.

**Comment by master7720** [comment] 2022-02-01 20:26
> vclip doesn't work on vanilla. also just break 2 blocks lmao

you know thats too hard for @dxzv666

**Comment by SIMULATAN** [comment] 2022-02-16 10:58
Iirc meteor rejects has a phase

**Closed** 2022-03-18 15:00 UTC
Labels: enhancement
