### ISSUE TITLE
Make a minimap!

### ISSUE THREAD

**Issue by XkenXwei** [MeteorDevelopment/meteor-client#875] opened 2021-05-30 11:16 UTC
Mini map ;)

just like those mods, can render players animals ect

**Comment by StormyBytes** [comment] 2021-05-30 11:18
Pretty sure this is a duplicate

**Comment by RoastedCheese** [comment] 2021-05-30 11:23
Just use another mod

**Comment by StormyBytes** [comment] 2021-05-30 12:43
Yes this is a duplicate of #665

**Comment by ClemGlacee** [comment] 2021-05-31 09:37
Use a mod

**Closed** 2021-06-01 16:08 UTC
Labels: enhancement
