### ISSUE TITLE
X-ray doesn't work

### ISSUE THREAD

**Issue by ImCoolK** [MeteorDevelopment/meteor-client#2280] opened 2022-05-10 17:58 UTC
### Describe the bug

I'm using the dev build and the features are AMAZING, only came across one bug, which when i turn on xray (X keybind), it flashes the chunks and just shows stuff normally. Thanks to me using the dev build, i can report that before it is uploaded. Thanks!

### Steps to reproduce

```bash
Step 1: Turn on x-ray (i use the keybind X)
End
```

### Meteor Version

0.4.9 Dev build 1473

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment] 2022-05-10 21:45
What does the keybind matter?
Potential duplicate of #2271 and #2240. So many duplicates.

**Comment by I-Got-You-Dead** [comment] 2022-05-10 23:13
have you checked and changed the opacity?

**Closed** 2022-05-11 14:57 UTC
Labels: bug

**Comment by glebby-thing** [comment] 2023-07-19 17:21
i have this to

**Comment by glebby-thing** [comment] 2023-07-19 17:22
but im on the mane release version 1.19.4

**Comment by C0rRupt3dDadda** [comment] 2023-08-07 11:17
I am on release 0.5.3 and X-ray does not work as intended for me neither. It does however work whilst in 3rd person with camera tweaks toggled on. Wall-Hack is not working as intended as well.
