### ISSUE TITLE
Some text cannot be displayed normally

### ISSUE THREAD

**Issue by Wuqibor666** [MeteorDevelopment/meteor-client#1454] opened 2021-09-04 04:42 UTC
### Describe the bug

I am a Chinese from China. I kill Meteor Client. I think it works better than Wrust Client.
There are some Chinese texts cannot be displayed in meteor. Such as item name, entity name. It's empty!
My game language is Chinese (简体中文 中国). If I switch my language to English, it can be displayed normally.
![image](https://user-images.githubusercontent.com/88495503/132082390-dc8e8bb1-0bf2-4646-ad20-643ef536c752.png)
I tried versions 0.4.5 and 0.4.6-1244, both of which have this problem. It is bad!
This problem occurs in the interface involving item / entity selection.
For example, Kill Aura's attack object selection and Screah's box selection.
![image](https://user-images.githubusercontent.com/88495503/132082625-4169f129-a016-4a53-a0fb-f47d80af8029.png)
But you can search in Chinese. (I entered "箱", which means box)
I hope this problem can be solved as soon as possible. If the display compatible with Chinese is troublesome, you can directly force the use of English.
Maybe my English is not so good, please forgive me.
In addition, if there is a need for multilingual adaptation, I can help translate it into Chinese
My Email: admin@wuqibor.gq

### Steps to reproduce

```bash
1.Open Minecraft
2.Open Meteor GUI
3.Open item choose GUI
```

### Meteor Version

0.4.5 and 0.4.6-1244

### Minecraft Version

1.16.5 and 1.17.1

### Operating System

Windows

**Comment by radiden** [comment] 2021-09-04 05:17
The problem is not in the client, the problem is the lack of CJK glyphs in the font JetBrains Mono, which is the default. You should either add a custom font with CJK glyphs to Meteor or disable the `Custom Font` option under the `Config` menu.

**Comment by MineGame159** [comment] 2021-09-04 14:19
Duplicate of #333

**Closed by MineGame159** 2021-09-04 14:19 UTC
Labels: bug
