### ISSUE TITLE
Villager Trade module

### ISSUE THREAD

**Issue by evo11211** [MeteorDevelopment/meteor-client#1041] opened 2021-06-14 04:12 UTC
**Describe the feature**
A Module that auto checks and resets a villager's trades to a specified trade then locks the villagers trades by trading with it

Example:
I wan't a mending villager. I select mending from a list of trades, then I activate the module, and finally place a lectern in front of the villager. After that point the client would check the villager's trades and if it is a mending book the client trades with the villager, if not it brakes the lectern and replaces it starting the cycle over.

**Comment by LittleDraily** [comment] 2021-06-14 06:49
I'm pretty sure villager trades are picked server side. If this is the case it would be almost impossible!

**Comment by seasnail8169** [comment] 2021-06-14 11:27
duplicate of #955 anyway

**Closed by seasnail8169** 2021-06-14 11:27 UTC
Labels: enhancement
