### ISSUE TITLE
[Bug] Rendering bug that crashes the game

### ISSUE THREAD

**Issue by BookWyrm114** [MeteorDevelopment/meteor-client#1919] opened 2022-01-09 22:01 UTC
### Describe the bug

The game crashes when trying to open the HUD editor, or some modules like ESP or nametags. This may be caused by using meteor in conjunction with some addons

Crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 1/9/22, 4:57 PM
Description: Unexpected error

java.lang.NoSuchFieldError: useTeamColor
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.handler$cmj000$onGetPlayerColor(PlayerUtils.java:535)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.getPlayerColor(PlayerUtils.java)
	at meteordevelopment.meteorclient.systems.hud.modules.CombatHud.lambda$render$0(CombatHud.java:215)
	at meteordevelopment.meteorclient.systems.hud.HudRenderer.end(HudRenderer.java:28)
	at meteordevelopment.meteorclient.systems.hud.HUD.onRender(HUD.java:161)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.client.gui.hud.InGameHud.handler$bll000$onRender(InGameHud:3041)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:416)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:856)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.handler$cmj000$onGetPlayerColor(PlayerUtils.java:535)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.getPlayerColor(PlayerUtils.java)
	at meteordevelopment.meteorclient.systems.hud.modules.CombatHud.lambda$render$0(CombatHud.java:215)
	at meteordevelopment.meteorclient.systems.hud.HudRenderer.end(HudRenderer.java:28)
	at meteordevelopment.meteorclient.systems.hud.HUD.onRender(HUD.java:161)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_329.handler$bll000$onRender(class_329.java:3041)
	at net.minecraft.class_329.method_1753(class_329.java:416)

-- Affected level --
Details:
	All players: 1 total; [class_746['BookWyrm_'/116974, l='ClientLevel', x=-3455.72, y=128.00, z=454.30]]
	Chunk stats: 1024, 529
	Level dimension: minecraft:the_nether
	Level spawn location: World: (-3457,128,459), Section: (at 15,0,11 in -217,8,28; chunk contains blocks -3472,0,448 to -3457,255,463), Region: (-7,0; contains chunks -224,0 to -193,31, blocks -3584,0,0 to -3073,255,511)
	Level time: 12667 game time, 316599125 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, 115004fd557f0802ee26a63b483fb94fd10e6eb6

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1804360304 bytes (1720 MiB) / 4630511616 bytes (4416 MiB) up to 15401484288 bytes (14688 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: spacedesk Graphics Adapter
	Graphics card #0 vendor: datronicsoft
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.1.334.150
	Graphics card #1 name: Radeon RX 590 Series
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x67df
	Graphics card #1 versionInfo: DriverVersion=27.20.22001.14011
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 40634.68
	Virtual memory used (MB): 17633.67
	Swap memory total (MB): 7936.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx14688m -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		architectury: Architectury 3.4.9
		baritone: Baritone 1.18-SNAPSHOT
		bettersneak: Better Sneak 1.0.0
		blue_endless_jankson: jankson 1.2.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		clumps: Clumps 8.0.4
		com_github_hube12_seed: SEED master-SNAPSHOT
		controlling: Controlling For Fabric 9.0.11
		cullleaves: Cull Leaves 2.3.2
		deathlog: DeathLog 0.2.4+1.18
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entityculling: EntityCulling-Fabric 1.3.3
		experiencebugfix: Experience Bug Fix 18
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f314
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		ferritecore: FerriteCore 4.0.0
		ias: In-Game Account Switcher 7.1.3
		ibeeditor: IBE Editor 2.0.10
		indium: Indium 1.0.2-alpha1+mc1.18
		iris: Iris 1.1.4
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.7
		meteor-client: Meteor Client 0.4.7-1390
		meteor-rejects: Meteor Rejects 0.1
		meteor-tweaks: Meteor Tweaks 1.0.5
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		mousetweaks: Mouse Tweaks 2.20
		multiconnect: MultiConnect 1.5.10
		multiconnect-api: MultiConnect API 1.5.10
		multiple-server-lists: Multiple Server Lists 2.0.1
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		orion: Orion 0.1
		pride: Pride Lib 1.1.0+1.17
		reeses-sodium-options: Reese's Sodium Options 1.3.0
		roughlyenoughitems: Roughly Enough Items 7.1.357
		smoothcoasters: SmoothCoasters 1.18.1-v1
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		spruceui: SpruceUI 3.3.0+1.17
		sspb: Sodium Shadowy Path Blocks 0.2.0
		starlight: Starlight 1.0.0+fabric.d0a3220
		tooltipfix: ToolTip Fix 1.0.4-1.18
		vector-addon: Vector Addon 0.2.6
		xaerominimap: Xaero's Minimap 21.23.0
		xaeroworldmap: Xaero's World Map 1.19.0
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 590 Series GL version 3.2.14739 Core Profile Forward-Compatible Context 21.6.1 27.20.22001.14011, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Meteor Client (meteor-client), Fabric Loader (fabricloader)

-- Meteor Client --
Version: 0.4.7
Dev Build: 1390

### Steps to reproduce

```bash
Install the build of meteor listed, as well as the addons meteor rejects, meteor tweaks, orion, and the unofficial addon vector then enable a nametags module or open the HUD editor
```

### Meteor Version

dev build 0.4.7 - 1390

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment] 2022-01-09 23:24
can you try without any addons

**Comment by BookWyrm114** [comment] 2022-01-10 13:56
Works fine without them, I'll do testing with the addons and see which one causes the problem, if it's none of those it's probably an incompatibility with another mod

**Comment by Theboiboi8** [comment] 2022-01-10 14:12
This is caused by Vector addon, will be fixed in new release

**Comment by Theboiboi8** [comment] 2022-01-10 14:12
for now If you really want Vector use meteor 1387 or lower

**Closed** 2022-01-10 14:28 UTC
Labels: bug
