### ISSUE TITLE
[Bug] Xray bugging out display on 1505

### ISSUE THREAD

**Issue by GavinGoGaming** [MeteorDevelopment/meteor-client#2417] opened 2022-06-17 22:38 UTC
### Describe the bug

xray bugs out torches, blocks, and just doesnt work in general.

If needed here is blocks
![image](https://user-images.githubusercontent.com/57292172/174409317-714213fa-7292-4c89-9dfb-edabd1db6ce4.png)
and opacity ive used 18 and 27

### Steps to reproduce

```bash
- Go in-game (I tested on multiplayer, with and without resource pack)
- Enable Xray
- Exit Menu
```

### Meteor Version

meteor-client 0.5.0 dev 1505

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)
- [X] This bug wasn't already reported.
(I have checked every bug report on github)

**Comment by SIMULATAN** [comment] 2022-06-18 07:06
Duplicate of #2240

**Closed** 2022-06-18 11:48 UTC
Labels: bug
