### ISSUE TITLE
Inv Move error

### ISSUE THREAD

**Issue by minimimike** [MeteorDevelopment/meteor-client#237] opened 2021-02-13 11:10 UTC
When i open any inventory, i walk backwards without pressing anything.

**Comment by simulatorwinner** [comment] 2021-02-15 12:54
doesn't happen to me, what client version ?

**Comment by bramceulemans** [comment] 2021-02-20 02:53
This happened to me too, the search tab is expanded and Gui Move is enabled.

**Comment by RedCarlos26** [comment] 2021-02-23 22:49
It happened to me before but I think it is fixed in 0.4.1

**Comment by RedCarlos26** [comment] 2021-03-14 05:14
It was fixed in 0.4.1, but it could still happen. It does not happen anymore in 0.4.2. It seems finally fixed entirely.

**Comment by RedCarlos26** [comment] 2021-03-21 19:11
I don't know why, but it is still happening sometimes. I don't know how to reproduce it, it is pretty random.

**Comment by RedCarlos26** [comment] 2021-03-30 02:53
I think it got fixed again. It is no longer happening to me

**Comment by RedCarlos26** [comment] 2021-04-01 12:27
It started to happen again (and it's way worse) since the dev build that rewrites the GUI.

**Comment by MineGame159** [comment] 2021-04-10 15:28
Should be fixed in d70ca1172f002aaf5c2ff6753c1c6ff5e663863f

**Closed by MineGame159** 2021-04-10 15:28 UTC
Labels: bug
